version: '3'
services:
  influxdb:
    image: influxdb:latest
    ports:
      - "8086:8086"
    networks:
      - app-network

  app:
    build: .
    depends_on:
      - influxdb
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
  